sudo: required
before_install:
  - gem install cocoapods -v '0.39.0'

osx_image: xcode7.2
language: objective-c

xcode_workspace: Actors.xcworkspace
xcode_scheme: Theater
xcode_sdk: iphonesimulator9.0
